# Generated by Django 4.2.5 on 2023-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_image', models.FileField(upload_to='')),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
