# Generated by Django 4.2.5 on 2023-09-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homepage',
            new_name='homepages',
        ),
    ]
